#
# ЭТО КОНФИГ ДЛЯ PRODUCTION (nginx.prod.conf)
#
server {
    # Nginx будет слушать на порту 80 внутри контейнера
    listen 80;
    # --- ИЗМЕНЕНИЕ: Указываем домен ---
    server_name orar.usarb.md;

    # Корень, где лежат собранные файлы
    root /usr/share/nginx/html;
    index index.html index.htm;

    # --- ЧАСТЬ 1 ---
    # Эта часть отдает React-приложение (index.html)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # --- ЧАСТЬ 2: ПРОКСИ ДЛЯ API ---
    # Эта часть перехватывает все запросы, начинающиеся с /api/
    location /api/ {
        # 'schedule-api-prod' - это имя сервиса из docker-compose.prod.yml
        # '3000' - это порт, который бэкенд слушает ВНУТРИ Docker-сети
        proxy_pass http://schedule-api-prod:3000;
        
        # 3. Стандартные заголовки для прокси
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Обработка ошибок
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}