version: '3.8'

services:
  # 1. ФРОНТЕНД (NGINX)
  schedule-client-prod:
    image: schedule-client-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - schedule-api-prod
    networks:
      - schedule-net-prod

  # 2. БЭКЕНД (NESTJS)
  schedule-api-prod:
    image: schedule-api-prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    environment:
      - DB_HOST=schedule-db-prod
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - API_PORT=${API_PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      
      # === ИСПРАВЛЕНИЕ ЗДЕСЬ ===
      # Имя переменной должно совпадать с тем, что в коде (строка 977 файла backend/src/google-calendar/google-calendar.service.ts)
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL} 
      
      - FRONTEND_URL=${FRONTEND_URL}
      # =========================
      
    ports:
      - "3000:3000"
    depends_on:
      schedule-db-prod:
        condition: service_healthy
    networks:
      - schedule-net-prod

  # 3. БАЗА ДАННЫХ (POSTGRES)
  schedule-db-prod:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      # ВАЖНО: Добавляем эту строку
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - schedule-net-prod

volumes:
  postgres_data_prod:

networks:
  schedule-net-prod:
    driver: bridge