version: '3.8'

services:
  # 1. ФРОНТЕНД (NGINX)
  schedule-client-prod:
    image: schedule-client-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod # Указываем наш новый production Dockerfile
    ports:
      - "8080:80" # Маппим порт 8080 на порт 80 Nginx внутри контейнера
    restart: unless-stopped
    depends_on:
      - schedule-api-prod
    networks:
      - schedule-net-prod

  # 2. БЭКЕНД (NESTJS)
  schedule-api-prod:
    image: schedule-api-prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod # Указываем наш новый production Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=schedule-db-prod # Внутреннее имя хоста БД
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - API_PORT=${API_PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      # --- ИЗМЕНЕНИЯ: Добавляем переменные для домена ---
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - FRONTEND_URL=${FRONTEND_URL}
      # --- КОНЕЦ ИЗМЕНЕНИЙ ---
    ports:
      - "3000:3000" # Открываем порт 3000
    depends_on:
      schedule-db-prod:
        condition: service_healthy # Ждем, пока БД будет готова
    networks:
      - schedule-net-prod

  # 3. БАЗА ДАННЫХ (POSTGRES)
  schedule-db-prod:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # ВАЖНО: Мы НЕ открываем порт 5432 наружу. 
    # Бэкенд общается с ней по внутренней сети (schedule-net-prod).
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data # Сохраняем данные
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - schedule-net-prod

volumes:
  postgres_data_prod: # Имя тома для данных БД

networks:
  schedule-net-prod: # Имя внутренней сети
    driver: bridge